import type { Event, Venue } from "@/types";

export const mockVenues: Venue[] = [
  {
    id: "v-sala-de-despecho",
    name: "Sala de Despecho",
    slug: "sala-de-despecho",
    type: "Copas & Fiesta",
    address: "Madrid",
    neighborhood: "Madrid",
    metro_station: "Centro",
    description: "Copas, pizzas, tacos y canciones que se cantan con sentimiento.",
    photo_urls: ["/venues/sala-de-despecho.png"],
    affiliated: true,
  },
  {
    id: "v1",
    name: "Teatro Kapital",
    slug: "teatro-kapital",
    type: "Nightclub",
    address: "Calle Atocha, 125",
    neighborhood: "Atocha",
    metro_station: "Atocha Renfe",
    description: "El templo de la noche madrileña. Siete plantas de música, shows y experiencias únicas.",
    photo_urls: ["https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=800&q=80"],
    affiliated: true,
  },
  {
    id: "v2",
    name: "Fortuny Home Club",
    slug: "fortuny-home-club",
    type: "Tardeo",
    address: "Calle Fortuny, 34",
    neighborhood: "Almagro",
    metro_station: "Alonso Martínez",
    description: "Elegancia y tardeos en el barrio más selecto de Madrid.",
    photo_urls: ["https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80"],
    affiliated: true,
  },
  {
    id: "v3",
    name: "Ramses",
    slug: "ramses",
    type: "Dinner & Show",
    address: "Plaza de la Independencia, 4",
    neighborhood: "Puerta de Alcalá",
    metro_station: "Retiro",
    description: "Gastronomía y espectáculo frente a la Puerta de Alcalá.",
    photo_urls: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80"],
    affiliated: false,
  },
  {
    id: "v4",
    name: "Picalagartos",
    slug: "picalagartos",
    type: "Rooftop",
    address: "Gran Vía, 44 (planta 8)",
    neighborhood: "Gran Vía",
    metro_station: "Gran Vía",
    description: "Las mejores vistas de Gran Vía con cócteles de autor y ambiente único.",
    photo_urls: ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80"],
    affiliated: true,
  },
  {
    id: "v5",
    name: "Teatro Barceló",
    slug: "teatro-barcelo",
    type: "Nightclub",
    address: "Calle Barceló, 11",
    neighborhood: "Tribunal",
    metro_station: "Tribunal",
    description: "Leyenda del Malasaña. Música electrónica y directos en un teatro del siglo XIX.",
    photo_urls: ["https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80"],
    affiliated: false,
  },
  {
    id: "v6",
    name: "Salmon Guru",
    slug: "salmon-guru",
    type: "Bar",
    address: "Calle del Echegaray, 21",
    neighborhood: "Las Letras",
    metro_station: "Sevilla",
    description: "Coctelería de autor en el corazón del barrio de las Letras. Entre los mejores bares del mundo.",
    photo_urls: ["https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800&q=80"],
    affiliated: false,
  },
];

export const mockEvents: Event[] = [
  {
    id: "e1",
    name: "Rosalía — MOTOMAMI World Tour",
    slug: "rosalia-motomami-madrid",
    category: "Clubs",
    subcategory: "Pop",
    venue_id: "v5",
    venue_name: "Teatro Barceló",
    neighborhood: "Tribunal",
    date_start: "2026-05-10",
    time_start: "21:30",
    price_from: 45,
    price_to: 120,
    currency: "€",
    short_description: "La artista más importante de su generación vuelve a Madrid.",
    poster_url: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
    ticket_url: "https://ticketmaster.es",
    affiliate_link: "https://ticketmaster.es",
    is_featured: true,
    is_tonight: false,
    status: "active",
    stars_rating: 4.9,
    tags: ["concierto", "pop", "español"],
  },
  {
    id: "e2",
    name: "Noche en Kapital — Open Bar",
    slug: "noche-kapital-open-bar",
    category: "Clubs",
    subcategory: "Club",
    venue_id: "v1",
    venue_name: "Teatro Kapital",
    neighborhood: "Atocha",
    date_start: "2026-04-20",
    time_start: "23:00",
    price_from: 20,
    price_to: 40,
    currency: "€",
    short_description: "Open bar y 7 plantas de música esta noche en Kapital.",
    poster_url: "https://images.unsplash.com/photo-1571266752726-f4d4d9c91b0a?w=800&q=80",
    ticket_url: "https://kapital.es",
    affiliate_link: "https://kapital.es",
    is_featured: true,
    is_tonight: true,
    status: "active",
    stars_rating: 4.7,
    tags: ["nightlife", "club", "open-bar"],
  },
  {
    id: "e3",
    name: "Real Madrid vs Barcelona — El Clásico",
    slug: "clasico-real-madrid-barcelona",
    category: "After Work",
    subcategory: "Fútbol",
    venue_id: "v1",
    venue_name: "Estadio Santiago Bernabéu",
    neighborhood: "Chamartín",
    date_start: "2026-05-03",
    time_start: "21:00",
    price_from: 80,
    price_to: 500,
    currency: "€",
    short_description: "El partido del año. Bernabéu en llamas.",
    poster_url: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&q=80",
    ticket_url: "https://realmadrid.com",
    is_featured: true,
    is_tonight: false,
    status: "active",
    stars_rating: 5.0,
    tags: ["fútbol", "deportes", "clasico"],
  },
  {
    id: "e4",
    name: "Fortuny Tardeo — Sábado Luxury",
    slug: "fortuny-tardeo-sabado",
    category: "Tardeos",
    subcategory: "Tardeo",
    venue_id: "v2",
    venue_name: "Fortuny Home Club",
    neighborhood: "Almagro",
    date_start: "2026-04-20",
    time_start: "17:00",
    price_from: 15,
    currency: "€",
    short_description: "El mejor tardeo de Madrid cada sábado desde las 17h.",
    poster_url: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
    ticket_url: "https://fortuny.es",
    affiliate_link: "https://fortuny.es",
    is_featured: false,
    is_tonight: true,
    status: "active",
    stars_rating: 4.6,
    tags: ["tardeo", "luxury", "sábado"],
  },
  {
    id: "e5",
    name: "La Traviata — Ópera en el Real",
    slug: "traviata-teatro-real",
    category: "Dinner Parties",
    subcategory: "Ópera",
    venue_id: "v3",
    venue_name: "Teatro Real",
    neighborhood: "Centro",
    date_start: "2026-04-25",
    time_start: "20:00",
    price_from: 30,
    price_to: 250,
    currency: "€",
    short_description: "Verdi en el escenario más elegante de Madrid.",
    poster_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
    ticket_url: "https://teatro-real.com",
    is_featured: false,
    is_tonight: false,
    status: "active",
    stars_rating: 4.8,
    tags: ["ópera", "teatro", "clásica"],
  },
  {
    id: "e6",
    name: "Cócteles & Atardecer — Picalagartos",
    slug: "coctel-atardecer-picalagartos",
    category: "Casual Drinks",
    subcategory: "Rooftop",
    venue_id: "v4",
    venue_name: "Picalagartos",
    neighborhood: "Gran Vía",
    date_start: "2026-04-20",
    time_start: "19:30",
    price_from: 12,
    price_to: 18,
    currency: "€",
    short_description: "Los mejores cócteles con vistas a Gran Vía al atardecer.",
    poster_url: "https://images.unsplash.com/photo-1484301548518-d0e0a5db0fc8?w=800&q=80",
    ticket_url: "https://picalagartos.es",
    is_featured: false,
    is_tonight: true,
    status: "active",
    stars_rating: 4.5,
    tags: ["rooftop", "cócteles", "atardecer"],
  },
  {
    id: "e7",
    name: "Mad Cool Festival 2026",
    slug: "mad-cool-festival-2026",
    category: "Clubs",
    subcategory: "Rock / Alternativo",
    venue_id: "v1",
    venue_name: "Recinto Ferial IFEMA",
    neighborhood: "Barajas",
    date_start: "2026-07-08",
    time_start: "17:00",
    price_from: 95,
    price_to: 220,
    currency: "€",
    short_description: "El festival más grande del verano madrileño.",
    poster_url: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80",
    ticket_url: "https://madcoolfestival.es",
    affiliate_link: "https://madcoolfestival.es",
    is_featured: true,
    is_tonight: false,
    status: "active",
    stars_rating: 4.7,
    tags: ["festival", "rock", "verano"],
  },
  {
    id: "e8",
    name: "Exposición Dalí — Fundación Mapfre",
    slug: "exposicion-dali-mapfre",
    category: "After Work",
    subcategory: "Exposición",
    venue_id: "v6",
    venue_name: "Fundación Mapfre",
    neighborhood: "Recoletos",
    date_start: "2026-04-22",
    time_start: "10:00",
    price_from: 12,
    currency: "€",
    short_description: "La colección más completa de Dalí en España en una sola exposición.",
    poster_url: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800&q=80",
    ticket_url: "https://fundacionmapfre.org",
    is_featured: false,
    is_tonight: false,
    status: "active",
    stars_rating: 4.6,
    tags: ["arte", "exposición", "dalí"],
  },
];

export const mockFeaturedEvents = mockEvents.filter((e) => e.is_featured);
export const mockTonightEvents = mockEvents.filter((e) => e.is_tonight);
